### ISSUE TITLE
Helloworld example giving syntax errors in M4L Ableton live 10

### ISSUE THREAD

**Issue by EMCP** [Cycling74/n4m-core-examples#13]
#### Nature of issue?

- [ X] Found a bug in an example
- [X ] Existing example enhancement
- [ ] Suggest a new example

I am unclear what I need to do, in order to work on the hello world example... Instead of using the provided device, I wanted to start with a device from scratch.  I think that might be a much more useful example as well... in any event, I started with a device I had working already and added the `node.script` `js <script_file_name>` command... but the hello world is getting syntax errors and refusing to start??

![image](https://user-images.githubusercontent.com/3691722/76168609-affccb00-6171-11ea-8259-a55a1af6e4f2.png)

any insight into what I can do is appreciated.  Having tough time with the devices and knowing how to get started modifying or logging to console.. seems to crash with no warning or not execute at all if I try to add `console.log()`

#### Details about the bug: 

- Max version: 
- Operating System: Mac OS
- Name of example: Hello World
- Steps to reproduce this:

**Comment by EMCP** [comment]
im thinking perhaps I am using features that are not yet in this version of nodejs .. ie `let`

**Comment by fde31** [comment]
Hi Erik

Tough to tell without the patch but looking at your screenshot and initial
report I’d make a guess that the syntax within the object is wrong. You’d
have to use something like

[node.script <filename>]

In your example it seems to be

[node.script js <filename>]

Which makes Max lookup a file in the search path called “js” which is
definitely causing problems.

Hope that helps?

**Comment by EMCP** [comment]
I think now I am satisfied that I mixed up the nodejs and js engines.. leading to problems .. also I was used to using more advanced JS features like `let` which I can simply back off when inside Max

**Comment by fde31** [comment]
Ok sure. You can use the modern EcmaScript syntax within the scripts running inside a [node.script]. For [js] that is not the case currently. However, transpiling your code might be an option if you'd like to use newer ES features within a [js] object.
